In [1]:
import numpy as np

### Создание numpy массива

In [3]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

### Глубокое копирование массива

In [7]:
B = A.copy()
B

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print('id A: {}\nid B: {}'.format(id(A), id(B)))

id A: 140591730554960
id B: 140591730554400


In [12]:
C = A
C

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
print('id A: {}\nid B: {}'.format(id(A), id(C)))

id A: 140591730554960
id B: 140591730554960


### Нулевой и единичный массивы

In [15]:
A = np.zeros((2,3))
A

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
B = np.ones((2,3))
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
A = np.array([[1,2,3], [4,5,6]])
B = np.zeros_like(A)
B

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
B =  np.ones_like(A)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
A = np.zeros((2,3), 'int')
A

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
A = np.zeros((2,3), 'complex')
A

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [29]:
B = np.ones((2,3), 'int')
B

array([[1, 1, 1],
       [1, 1, 1]])

In [31]:
B = np.ones((2,3), 'complex')
B

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])

### Массив с шагом

In [22]:
A = np.arange(2.5, 7, .5)
A

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [23]:
A = np.arange(5)
A

array([0, 1, 2, 3, 4])

In [25]:
A = np.arange(10, 15)
A

array([10, 11, 12, 13, 14])

### Приведение типов

In [34]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'others': [bool, object, bytes, str, numpy.void]}

In [33]:
A = np.ones((3,2))
B = A.astype('str')
B

array([['1.0', '1.0'],
       ['1.0', '1.0'],
       ['1.0', '1.0']], dtype='<U32')